### ISSUE TITLE
Use parallelization for running AVA tests

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#1450]
When we used AVA's internal parallelization (the tests are run in separate process) we got too many "NoSuchSessionErrors" from selenium, so we can to set concurrency to 1.

I thought we should try using Travis's parallelization instead, which AVA has a hook build into for. In this case, we can run sections of the AVA tests in separate VMs instead of separate process. I start to experiment with this in a PR on the Bocoup branch: https://github.com/bocoup/aria-practices/pull/21

I'd like to test it more before opening a PR, but the tests ran in 6 minutes instead of 20, I'm confused why the speed up is so great and afraid not all tests are running. This is the main change to `.travis.ci`:

```
    - stage: Test
      name: AVA Regression Tests
      addons:
        firefox: latest
      script: scripts/regression-tests.sh
      env:
        - TEST_WAIT_TIME=1000
        - CI_NODE_TOTAL=2
        - CI_NODE_INDEX=0

    - stage: Test
      name: AVA Regression Tests
      addons:
        firefox: latest
      script: scripts/regression-tests.sh
      env:
        - TEST_WAIT_TIME=1000
        - CI_NODE_TOTAL=2
        - CI_NODE_INDEX=1
```
